// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN1xUMyES8gLSApoHg0SpaTlv0dtl6oBM',
    appId: '1:772895147005:web:b5917a26f56174d8f5cf94',
    messagingSenderId: '772895147005',
    projectId: 'yks-asistanim-30502',
    authDomain: 'yks-asistanim-30502.firebaseapp.com',
    storageBucket: 'yks-asistanim-30502.firebasestorage.app',
    measurementId: 'G-RWHWDS8JTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO3swbg9v1_8XX78AFYKIRU_9lf3cv5RI',
    appId: '1:772895147005:android:7d519caec13bbf02f5cf94',
    messagingSenderId: '772895147005',
    projectId: 'yks-asistanim-30502',
    storageBucket: 'yks-asistanim-30502.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCge-7rmOpFYIugOEbyfQKDVpGBPyK43rk',
    appId: '1:772895147005:ios:5efa0c5ede43195ff5cf94',
    messagingSenderId: '772895147005',
    projectId: 'yks-asistanim-30502',
    storageBucket: 'yks-asistanim-30502.firebasestorage.app',
    iosBundleId: 'com.example.ilkProjem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCge-7rmOpFYIugOEbyfQKDVpGBPyK43rk',
    appId: '1:772895147005:ios:5efa0c5ede43195ff5cf94',
    messagingSenderId: '772895147005',
    projectId: 'yks-asistanim-30502',
    storageBucket: 'yks-asistanim-30502.firebasestorage.app',
    iosBundleId: 'com.example.ilkProjem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN1xUMyES8gLSApoHg0SpaTlv0dtl6oBM',
    appId: '1:772895147005:web:d9123ba0d2190093f5cf94',
    messagingSenderId: '772895147005',
    projectId: 'yks-asistanim-30502',
    authDomain: 'yks-asistanim-30502.firebaseapp.com',
    storageBucket: 'yks-asistanim-30502.firebasestorage.app',
    measurementId: 'G-HBG6XRW93R',
  );
}
